name: Foreclosure Sales Scraper

on:
  schedule:
    - cron: "0 9 * * *"  # runs every day at 9 AM UTC (adjust as needed)
  workflow_dispatch:      # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas google-api-python-client google-auth

      - name: Run scraper
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main_lightweight.py
